_wandb:
    value:
        cli_version: 0.19.5
        m: []
        python_version: 3.8.10
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.8.10
            "5": 0.19.5
            "8":
                - 5
            "12": 0.19.5
            "13": linux-x86_64
batch_size:
    value: 64
learning_rate:
    value: 0.06798021064831941
momentum:
    value: 0.9
n_epochs:
    value: 5
optimizer:
    value: adamw
weight_decay:
    value: 0
